"""Cloth-on-model generation with Nano Banana Pro.

A PORT of vnyx-api's `services/banana-nano.ts`, and deliberately a faithful one.
Both paths write into the same gallery, so a product backfilled from here sits
next to products generated by the analyze worker. If the prompts drift, the two
sets of renders stop looking like the same shop — different framing, a different
kind of model, a different backdrop — and that is visible to a customer in a way
no test would catch. `tests/test_nanobanana_prompt.py` pins the text for exactly
that reason.

The same reasoning fixes the model id in policy rather than leaving it to an env
var: `gemini-3-pro-image-preview` is what the TypeScript side calls, and changing
it on one side alone is the drift described above.


WHAT THIS ADDS OVER THE TYPESCRIPT

  * FRONT-ONLY PRODUCTS. `generateClothOnModel` takes a front and a back buffer;
    the regenerate worker quietly passes `imageBuffers[1] || imageBuffers[0]`, so
    a product with one photograph silently hands the model the same picture twice
    and lets it work out that the back is unknown. Here that is explicit: the
    prompt SAYS the rear was never photographed and must be inferred from the
    garment's construction, and the caller is told `back_inferred` so it can be
    surfaced rather than shipped quietly.

  * GAP FILLING. The TypeScript regenerates all five views or one clicked tile.
    Most products missing imagery are missing ONE view, so this generates exactly
    the views asked for and takes the product's existing AI_FRONT render as the
    identity reference — the same `frontReferenceImage` mechanism, pointed at a
    render that already exists. One call instead of five, and the new view matches
    the model already in the gallery.
"""

from __future__ import annotations

import base64
import concurrent.futures
import io
import logging
import os
import re
import threading
import time
from dataclasses import dataclass
from typing import Any

from app.imaging import openai_image
from app.net import fetch_all, genai_client_args
from app.models import GeneratedView, ImagerySettings

log = logging.getLogger("hermes.imaging.nanobanana")

# Internal short names, matching the TypeScript, mapped to the VNYX
# `ProductMediaView` values the caller stores. Keeping both is what lets the
# prompt code read like its source while the API speaks the schema's language.
VIEW_TO_MEDIA: dict[str, str] = {
    "front": "AI_FRONT",
    "back": "AI_BACK",
    "front34": "AI_FRONT_34",
    "back34": "AI_BACK_34",
    "closeup": "AI_CLOSEUP",
}
MEDIA_TO_VIEW: dict[str, str] = {v: k for k, v in VIEW_TO_MEDIA.items()}

# Canonical gallery order — front¾, back¾, front, back, close-up. The three-quarter
# views lead so they become the product's primary images. Mirrored from
# analyze.worker.ts and regenerate-image.worker.ts; the order matters because
# `rebuildMediaCache` ranks AI views in this sequence.
VIEW_ORDER = ["front34", "back34", "front", "back", "closeup"]

# Ported verbatim from helpers/formatters.ts. Substring matching here is correct
# and intentional — unlike the footwear test, which must be word-boundary.
BOTTOM_GARMENT_KEYWORDS = [
    "bottom", "pant", "jean", "skirt", "trouser", "short", "legging", "jogger",
    "denim",
]
TOP_GARMENT_KEYWORDS = [
    "top", "shirt", "blouse", "tee", "t-shirt", "tshirt", "hoodie", "sweater",
    "sweatshirt", "knit", "jumper", "cardigan", "tank", "polo",
]

BODY_TYPE_DESCRIPTORS: dict[str, str] = {
    "xs": "very petite and slim with a narrow frame, slim shoulders, slim waist and slim hips (size XS)",
    "s": "slim and lean with a slender frame (size S)",
    "m": "average, balanced proportions with a standard frame (size M)",
    "l": "full-figured with curvier hips, fuller bust and softer waistline (size L)",
    "xl": "plus-size with a noticeably fuller, curvier figure, broader shoulders, fuller bust, waist and hips (size XL)",
    "xxl": "extended plus-size with a voluptuous, full-bodied figure, prominently fuller bust, waist and hips (size XXL)",
}

_AGE_MAP = {
    "young": "young",
    "young adult": "young adult",
    "mid-age": "middle-aged",
    "middle-aged": "middle-aged",
    "old": "mature",
    "elder/seniors": "elderly",
    "teens": "teenage",
    "babies/children": "child",
}

_BACKGROUND_PROMPTS = {
    "bg_white": "white square with soft gray shading around its perimeter, clean minimalist background with gentle vignette effect, pure white center gradually transitioning to very light gray towards the edges",
    "bg_black": "very dark black background with coarse fibrous texture like denim or heavily woven textile, deep shadow with subtle dark grey patterns and fine irregular lines creating a subtle visual grain",
    "bg_blue": "smooth solid sky blue background with subtle gradient, bright and clean light blue transitioning from pale cyan in the center to slightly deeper saturated blue towards the edges, uniform and seamless texture",
    "bg_lime": "plain soft muted yellowish-green background, pale chartreuse or light olive green with gentle gradient, subtle luminous glow emanating from the center with fine uniform texture resembling matte paper",
}
_SIMPLE_COLORS = {
    "white": "clean white background",
    "black": "solid black background",
    "gray": "neutral gray background",
    "grey": "neutral gray background",
    "transparent": "transparent background",
    "studio": "professional studio background",
}


# Longest edge of a source photograph handed to the model, and the JPEG quality
# it is re-encoded at.
#
# The originals are 6 MB camera files. The model does not need that, the upload
# is the slowest part of a call, and on a rate-limited pub-*.r2.dev host a 6 MB
# GET is the one that gets cut off mid-body. The TypeScript path never sees this
# because the analyze worker feeds it already-compressed files; this path reads
# straight from R2, so it compresses here instead.
_SOURCE_MAX_PX = 1536
_SOURCE_QUALITY = 88


def compress_source(data: bytes) -> bytes:
    """Downscale to a sane size and flatten to JPEG.

    Flattening matters as much as the resize: a cut-out PNG has a transparent
    background, and every part is declared to the API as image/jpeg. Compositing
    onto white first means the model sees a clean garment on a white field rather
    than however it chooses to interpret an alpha channel it was told is opaque.

    Returns the input untouched if it cannot be decoded — an unreadable buffer is
    the caller's problem to report, not this function's to swallow.
    """
    try:
        from PIL import Image

        img = Image.open(io.BytesIO(data))
        img.load()
        if img.mode in ("RGBA", "LA", "P"):
            flat = Image.new("RGB", img.size, (255, 255, 255))
            img = img.convert("RGBA")
            flat.paste(img, mask=img.split()[-1])
            img = flat
        else:
            img = img.convert("RGB")
        img.thumbnail((_SOURCE_MAX_PX, _SOURCE_MAX_PX), Image.Resampling.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, "JPEG", quality=_SOURCE_QUALITY)
        return buf.getvalue()
    except Exception as exc:  # noqa: BLE001
        log.warning("could not compress a source image (%s); sending as-is",
                    type(exc).__name__)
        return data


def _lower(value: Any) -> str:
    return value.lower().strip() if isinstance(value, str) else ""


def _trait(value: str | None) -> str | None:
    """A personality trait worth putting in the prompt.

    'any' is the UI's "no preference" and must not reach the model as a literal
    — "any skin tone" is an instruction, and a worse one than saying nothing.
    """
    if not value or not value.strip():
        return None
    text = value.strip()
    return None if text.lower() == "any" else text


def _canonical_gender(value: str | None) -> str | None:
    """'male' | 'female' | None, from any of the spellings in use."""
    low = _lower(value)
    if low in ("men", "man", "male"):
        return "male"
    if low in ("women", "woman", "female"):
        return "female"
    return None


def choose_personality(
    settings: ImagerySettings, product_gender: str | None, rng: Any = None
) -> dict[str, Any] | None:
    """Pick one of the tenant's named models for this product.

    Mirrors analyze.worker.ts. A personality carries its own gender, so a men's
    product only draws from male personalities and a women's only from female —
    otherwise the catalog shows a woman modelling a men's shirt. A personality
    with no gender set is legacy and stays eligible for anything, and when the
    product's own gender is unknown no filter applies at all.

    Random by design: the point is a catalog that looks like a shop with several
    models rather than one person wearing everything. Callers that need the SAME
    face again — filling in a missing view beside an existing render — must reuse
    the stored traits instead of calling this.
    """
    if not settings.personalities_enabled:
        return None

    wanted = _canonical_gender(product_gender)
    pool = [
        p for p in settings.personalities
        if isinstance(p, dict) and p.get("enabled") is not False
        and (
            wanted is None
            or _canonical_gender(p.get("gender")) is None
            or _canonical_gender(p.get("gender")) == wanted
        )
    ]
    if not pool:
        return None

    import random

    return (rng or random).choice(pool)


def apply_personality(
    settings: ImagerySettings, personality: dict[str, Any] | None
) -> ImagerySettings:
    """Flatten a personality's traits onto a copy of the settings.

    The personality's `age` OVERRIDES the tenant default — a cast entry says "24"
    where the tenant setting says "young adult", and the specific number is the
    point of having named models. Ethnicity and body type deliberately stay on
    the tenant defaults, matching the TypeScript.

    Accepts BOTH shapes this is called with, which differ in one key: a cast
    entry from `ImageGenerationSettings.personalities` carries `name`, while the
    copy stored on `Product.imageSettings` carries `personalityName`. Reading
    only the first silently dropped the name on the reuse path, so a product's
    saved model came back anonymous and the next gap-fill drew a new one.
    """
    if not personality:
        return settings

    return settings.model_copy(update={
        "age": personality.get("age") or settings.age,
        "skin_tone": personality.get("skinTone"),
        "hair_color": personality.get("hairColor"),
        "hair_style": personality.get("hairStyle"),
        "tattoos": personality.get("tattoos"),
        "piercings": personality.get("piercings"),
        "personality_notes": personality.get("notes")
        or personality.get("personalityNotes"),
        "personality_name": personality.get("name")
        or personality.get("personalityName"),
    })


def is_bottom_garment(category: str | None, sub_category: str | None) -> bool:
    cat, sub = _lower(category), _lower(sub_category)
    return any(k in cat or k in sub for k in BOTTOM_GARMENT_KEYWORDS)


# WORD-BOUNDARY for these two, unlike the top/bottom lists above, which match on
# substrings. A substring "cap" classifies CAPRI TROUSERS as headwear and a
# substring "boot" classifies BOOTCUT JEANS as footwear — both real categories,
# and both would be framed as something the customer is not buying.
_FOOTWEAR_RE = re.compile(
    r"\b(footwear|shoes?|sneakers?|trainers?|boots?|sandals?|heels?|loafers?"
    r"|pumps?|mules?|clogs?|espadrilles?|slippers?)\b",
    re.IGNORECASE,
)

# Worn, but not on the torso or the legs — so neither the top framing nor the
# bottom framing puts the product anywhere near the middle of the frame.
_ACCESSORY_RE = re.compile(
    r"\b(accessor(?:y|ies)|bags?|backpacks?|rucksacks?|handbags?|totes?|purses?"
    r"|satchels?|clutch(?:es)?|caps?|hats?|beanies?|belts?|scar(?:f|ves)"
    r"|gloves?|wallets?|sunglasses|watch(?:es)?|jewell?ery|ties?)\b",
    re.IGNORECASE,
)


def is_footwear_garment(category: str | None, sub_category: str | None) -> bool:
    return any(_FOOTWEAR_RE.search(v or "") for v in (category, sub_category))


def is_accessory_garment(category: str | None, sub_category: str | None) -> bool:
    return any(_ACCESSORY_RE.search(v or "") for v in (category, sub_category))


def accessory_region(category: str | None, sub_category: str | None) -> str:
    """Where on the body an accessory actually sits.

    One class, but the crop has to follow the product: a bag hangs at the
    shoulder, a cap sits on the head, a belt at the waist. Framing all of them
    the same way reproduces the bug this class exists to fix, just at a
    different height.
    """
    text = f"{_lower(category)} {_lower(sub_category)}"
    if re.search(r"\b(caps?|hats?|beanies?|sunglasses)\b", text):
        return "head and shoulders"
    if re.search(r"\b(belts?)\b", text):
        return "waist and hips"
    if re.search(r"\b(scar(?:f|ves)|ties?)\b", text):
        return "neck and shoulders"
    if re.search(r"\b(gloves?|watch(?:es)?)\b", text):
        return "hands and forearms"
    return "shoulder and torso"


def classify_garment_type(category: str | None, sub_category: str | None) -> str | None:
    """'footwear' | 'accessory' | 'bottom' | 'top' | None.

    The product CATEGORY, never `mannequinType` — the mobile and decision flows
    set mannequinType to a model type ("Men Top", "Women Top", "Kids") regardless
    of the garment, so a pair of jeans arrives as "Men Top" and would be framed
    and styled as a shirt.

    Footwear and accessories are tested FIRST because they are the narrowest and
    the most specific: their regexes require whole words, so anything they match
    really is that thing, whereas the top/bottom lists match substrings and would
    happily claim "Backpacks & Bags" for nothing at all.
    """
    if is_footwear_garment(category, sub_category):
        return "footwear"
    if is_accessory_garment(category, sub_category):
        return "accessory"
    if is_bottom_garment(category, sub_category):
        return "bottom"
    cat, sub = _lower(category), _lower(sub_category)
    if any(k in cat or k in sub for k in TOP_GARMENT_KEYWORDS):
        return "top"
    return None


def background_image_prompt(value: str | None) -> str:
    if not value:
        return ""
    if value in _BACKGROUND_PROMPTS:
        return _BACKGROUND_PROMPTS[value]
    if value.startswith("#"):
        return f"solid {value} color background"
    return _SIMPLE_COLORS.get(value.lower(), value)


def resolve_aspect_ratio(value: str | None, supported: list[str]) -> str | None:
    """None means "apply no constraint" — 'auto', empty, or unsupported.

    '5:7' is offered in the UI to mirror the image editor but has no native Gemini
    equivalent, so it maps to the closest supported portrait ratio.
    """
    if not value or value == "auto":
        return None
    if value == "5:7":
        return "3:4"
    return value if value in supported else None


def resolve_image_size(value: str | None, default: str = "2K") -> str:
    upper = (value or "").upper()
    return upper if upper in ("1K", "2K", "4K") else default


# --------------------------------------------------------------------------- #
# The prompt
# --------------------------------------------------------------------------- #

@dataclass
class PromptContext:
    """Everything the prompt builder reads, resolved once per product."""

    settings: ImagerySettings
    category: str | None = None
    sub_category: str | None = None
    mannequin_type: str | None = None
    # Overrides the tenant default. The analyze worker drives model gender from
    # the PRODUCT's own gender rather than the tenant setting, and this keeps a
    # backfilled render consistent with the ones already on the catalog.
    gender: str | None = None
    custom_prompt: str | None = None
    # No back photograph exists, so the rear is inferred rather than observed.
    back_inferred: bool = False
    # The model's identity comes from a render the product ALREADY has (the
    # reference image), not from a description: the personality trait lines are
    # left out of the prompt, so nothing in words can contradict the picture.
    # MID-000569 (17 Sep 2026): a close-up re-rendered beside four renders of a
    # blonde woman came back with a dark-haired one — the reference said one
    # person, a freshly cast personality described another, and the description
    # won. No stored traits, a reference in hand: describe nobody.
    identity_from_reference: bool = False


def build_prompt(view: str, ctx: PromptContext, has_front_reference: bool) -> str:
    """The full instruction for one view.

    Assembled in the same order as `generateSingleImage` in banana-nano.ts, and
    the wording of each clause is that function's. Reordering or rewording it is a
    visible change to the catalog, not a refactor.
    """
    s = ctx.settings
    mannequin_lower = _lower(ctx.mannequin_type)
    garment_class = classify_garment_type(ctx.category, ctx.sub_category) or (
        "bottom" if "bottom" in mannequin_lower
        else "top" if "top" in mannequin_lower
        else None
    )
    is_bottom = garment_class == "bottom"
    is_footwear = garment_class == "footwear"
    is_accessory = garment_class == "accessory"
    # Where the camera goes for an accessory. Only read when is_accessory.
    region = accessory_region(ctx.category, ctx.sub_category)

    if view == "front":
        view_description = "Full-body front view (head to feet)"
    elif view == "back":
        view_description = "Full-body back view (head to feet)"
    elif view == "front34":
        if is_footwear:
            view_description = (
                "Lower-leg three-quarter front view (knee to floor) focused on the "
                "footwear"
            )
        elif is_accessory:
            view_description = (
                f"Three-quarter front view cropped to the {region}, focused on the "
                "accessory"
            )
        elif is_bottom:
            view_description = (
                "Lower-body three-quarter front view (waist to feet) focused on the "
                "bottoms"
            )
        else:
            view_description = (
                "Tighter three-quarter-length (knee-up) front view — feet cropped out "
                "of frame, NOT a full-body shot"
            )
    elif view == "back34":
        if is_footwear:
            view_description = (
                "Lower-leg three-quarter back view (knee to floor) focused on the "
                "footwear, seen from behind"
            )
        elif is_accessory:
            view_description = (
                f"Three-quarter back view cropped to the {region}, focused on the "
                "accessory"
            )
        elif is_bottom:
            view_description = (
                "Lower-body three-quarter back view (waist to feet) focused on the "
                "bottoms"
            )
        else:
            view_description = (
                "Tighter three-quarter-length (knee-up) back view — feet cropped out "
                "of frame, NOT a full-body shot"
            )
    else:
        if is_footwear:
            view_description = (
                "Medium close-up of the footwear as worn (upper, laces and sole "
                "edge) — not an extreme macro"
            )
        elif is_accessory:
            view_description = (
                f"Medium close-up of the accessory as worn at the {region} — not an "
                "extreme macro"
            )
        elif is_bottom:
            view_description = (
                "Medium close-up of the bottoms on the model (hip/thigh/knee detail) "
                "— not an extreme macro"
            )
        else:
            view_description = (
                "Medium close-up of the upper garment on the model (neckline/chest "
                "detail) — not an extreme macro"
            )

    prompt = "Professional studio photography"

    if s.background:
        bg = background_image_prompt(s.background)
        prompt += f", {bg}" if bg else f", {s.background} background"
    else:
        prompt += ", white background"

    if s.theme:
        prompt += f", {s.theme} style"

    is_kids = ctx.mannequin_type == "Kids"
    model_parts: list[str] = []
    if not is_kids and s.ethnicity and s.ethnicity != "any":
        model_parts.append(s.ethnicity)
    if not is_kids and s.age and s.age != "any":
        model_parts.append(
            f"{s.age}-year-old" if s.age.isdigit()
            else _AGE_MAP.get(s.age, s.age)
        )

    # Model gender comes from the PRODUCT, not the tenant default and never from
    # mannequinType — that only frames the garment type. Kids suppresses gender
    # entirely and renders a child model.
    resolved_gender = (ctx.gender or s.gender) if not is_kids else None
    if resolved_gender:
        model_parts.append(resolved_gender)

    model_descriptor = (
        "child fashion model" if is_kids
        else f"{' '.join(model_parts)} fashion model" if model_parts
        else "fashion model"
    )
    prompt += f", {model_descriptor} wearing this clothing item"

    # Without this the model is often rendered in the featured garment alone — a
    # top with bare legs. The uploaded garment stays the hero; everything it does
    # not cover gets plain neutral clothing.
    prompt += (
        ". IMPORTANT STYLING: The provided clothing item is the hero product and "
        "must be worn and shown exactly as in the reference images. The model must "
        "be FULLY and appropriately dressed for a professional fashion catalog — "
        "never partially undressed, never in underwear only, and never with bare "
        "hips or bare legs exposed."
    )
    if garment_class == "top":
        prompt += (
            " Since the featured product is a top, pair it with simple, plain, "
            "neutral-colored bottoms (e.g. plain trousers, jeans, or shorts) that "
            "do not distract from the product."
        )
    elif garment_class == "bottom":
        prompt += (
            " Since the featured product is a bottom, pair it with a simple, plain, "
            "neutral-colored top that does not distract from the product."
        )
    elif garment_class == "footwear":
        # The hem instruction is the whole point. A full-length trouser breaks
        # over the shoe and hides the very thing being sold, which is how the
        # existing footwear renders ended up as pictures of an invented outfit
        # with a few pixels of sandal at the bottom edge.
        prompt += (
            " The featured product is the FOOTWEAR. Dress the model in a simple, "
            "plain, neutral-colored outfit with CROPPED OR ROLLED trouser hems that "
            "stop clearly ABOVE the ankle, so the shoes are fully visible and "
            "unobstructed — no long hems breaking over the shoe, no maxi skirt or "
            "wide leg covering it. Both shoes are worn, and nothing in the outfit "
            "competes with them for attention."
        )
    elif garment_class == "accessory":
        prompt += (
            f" The featured product is the ACCESSORY, worn at the {region}. Dress "
            "the model in a simple, plain, neutral-colored outfit that does not "
            "compete with it, and make sure the accessory is worn naturally, fully "
            "visible and never hidden by hair, a sleeve or an arm."
        )
    else:
        prompt += (
            " Complete the outfit with simple, plain, neutral-colored complementary "
            "garments (bottoms and/or top as needed) that do not distract from the "
            "product."
        )

    if not is_kids and s.body_type:
        descriptor = BODY_TYPE_DESCRIPTORS.get(s.body_type.lower())
        if descriptor:
            prompt += (
                f". CRITICAL: The model MUST have a {descriptor} body type. The body "
                f"proportions, frame, silhouette, and the way the garment drapes and "
                f"fits must clearly and visibly reflect this exact size. Do not "
                f"default to a standard runway/sample-size body — the body shape and "
                f"size are non-negotiable and must match the specified size"
            )

    # The selected personality's traits. Skipped for Kids, and any 'any'/empty
    # value is ignored — `trait()` below is the TypeScript's own guard.
    #
    # Without this every render is a generic model and the tenant's cast of 20
    # named personalities has no effect on anything, which makes a catalog that
    # looks like one person wearing the entire shop.
    #
    # Also skipped when the identity comes from a reference render (see
    # PromptContext.identity_from_reference): a trait in words that differs from
    # the person in the picture is an instruction to draw someone else.
    if not is_kids and not ctx.identity_from_reference:
        skin_tone = _trait(s.skin_tone)
        if skin_tone:
            prompt += f", {skin_tone} skin tone"

        hair_color, hair_style = _trait(s.hair_color), _trait(s.hair_style)
        if hair_color or hair_style:
            prompt += f", {' '.join(x for x in (hair_color, hair_style) if x)} hair"

        tattoos = _trait(s.tattoos)
        if tattoos:
            prompt += f". The model has visible tattoos: {tattoos}."

        piercings = _trait(s.piercings)
        if piercings:
            prompt += f" Piercings: {piercings}."

        notes = _trait(s.personality_notes)
        if notes:
            prompt += f" {notes}"

    is_back_view = view in ("back", "back34")
    is_three_quarter = view in ("front34", "back34")

    if view == "closeup":
        if is_footwear:
            close_up_framing = (
                " Frame this as a medium CLOSE-UP of the FOOTWEAR as worn on the "
                "model: a crop from roughly mid-calf down to the floor, with BOTH "
                "shoes filling most of the frame. The upper, laces or fastening, the "
                "toe shape and the sole edge must all be clearly visible, with the "
                "material texture and stitching sharp and in focus. Do NOT show the "
                "model's torso, face or head. This is closer than the three-quarter "
                "shot, but it is NOT an extreme macro — do NOT zoom so far that only "
                "material fills the frame; keep both complete shoes and a little of "
                "the floor visible for context."
            )
        elif is_accessory:
            close_up_framing = (
                " Frame this as a medium CLOSE-UP of the ACCESSORY as worn at the "
                f"{region}: a crop centred on the product so that it fills most of "
                "the frame, with its hardware, fastening, strap or brim, material "
                "texture and stitching sharp and in focus. Show enough of the body "
                "around it that it reads as WORN rather than as a product cut-out. "
                "This is closer than the three-quarter shot, but it is NOT an extreme "
                "macro — keep the whole accessory inside the frame."
            )
        elif is_bottom:
            close_up_framing = (
                " Frame this as a medium CLOSE-UP of the bottoms (trousers/skirt/"
                "shorts) as worn on the model: a crop focused on the hip-to-thigh/"
                "knee area showing the waistband, pockets, fly/zip and the key design "
                "detail, with the fabric texture, weave/knit and stitching sharp and "
                "in focus. Center the BOTTOMS garment on the lower body — do NOT show "
                "the model's chest, face or head. This is closer than the "
                "three-quarter shot, but it is NOT an extreme macro — do NOT zoom in "
                "so far that only fabric fills the frame; keep a recognisable portion "
                "of the bottoms on the lower body visible for context."
            )
        else:
            close_up_framing = (
                " Frame this as a medium CLOSE-UP of the upper part of the garment as "
                "worn on the model: a chest-up crop framed roughly from the "
                "shoulders/neckline down to the mid-torso (upper chest area). The "
                "collar/neckline, shoulders, upper chest and the key design detail "
                "should be clearly visible together with some surrounding context, and "
                "the fabric texture, weave/knit and stitching should be sharp and in "
                "focus. This is closer than the three-quarter shot, but it is NOT an "
                "extreme macro — do NOT zoom in so far that only fabric fills the "
                "frame; keep a recognisable portion of the garment on the upper body "
                "visible for context."
            )
        prompt += (
            f". CRITICAL: Keep the EXACT SAME garment, fabric, colour and details as "
            f"shown in the reference images (the front reference establishes the "
            f"model and how the garment sits).{close_up_framing}"
            if has_front_reference else f".{close_up_framing}"
        )
    elif is_back_view:
        # Passing the front image as an "EXACT SAME model" reference tends to make
        # the model echo the front-facing pose, so the camera position has to be
        # stated in the strongest terms or the back view comes out looking like
        # the front.
        prompt += (
            ". CRITICAL — REAR (BACK) VIEW: Photograph the model strictly FROM "
            "BEHIND, with the model facing directly AWAY from the camera. Show ONLY "
            "the back of the model: the back of the head and hair, the back of the "
            "shoulders and torso, and the BACK of the garment. The model's face, "
            "chest, and the front of the garment MUST NOT be visible at all — the "
            "model's back is fully turned to the camera. This is a true 180° rear "
            "view, NOT a front, side, or angled view."
        )
        prompt += (
            " Use the EXACT SAME model as in the front reference image (identical "
            "gender, hair type, hair color, skin tone, body type, tattoos, "
            "piercings) — only the camera position changes: it is now directly "
            "behind the model."
            if has_front_reference else
            " Keep the EXACT SAME model as the front view (identical gender, hair "
            "type, hair color, skin tone, body type, tattoos, piercings) — only the "
            "camera position changes: it is now directly behind the model."
        )
        # The one clause with no counterpart in the TypeScript.
        #
        # Without a back photograph the reference images show the front twice, and
        # the model will happily read the second one as the rear and reproduce
        # front-facing detail — a chest print appearing between the shoulder
        # blades. Saying the rear is unknown gets a plausible plain back instead of
        # a confidently wrong one.
        if ctx.back_inferred:
            prompt += (
                " NOTE: no photograph of the garment's reverse exists — every "
                "supplied reference image shows the FRONT. Do NOT copy front-facing "
                "detail onto the back. Infer the reverse from the garment's "
                "construction, cut, seams and fabric: unless the garment type "
                "clearly implies otherwise, render the back as the plain, "
                "undecorated counterpart of the front, carrying the same colour, "
                "material and finish but none of its front-only graphics, prints, "
                "pockets or fastenings."
            )
    else:
        prompt += (
            ". Use the EXACT SAME model as shown in the front reference image — "
            "identical gender, hair type, hair color, skin tone, body type, tattoos, "
            "piercings, and all physical characteristics. The model faces the camera."
            if has_front_reference else
            ". Remember the model's characteristics (gender, hair type, hair color, "
            "skin tone, body type, tattoos, piercings) as they must be used "
            "identically in the other views."
        )

    if view in ("front", "back"):
        prompt += (
            " Capture a FULL-LENGTH, full-body shot: the entire model is visible "
            "from the very top of the head/hair all the way down to the FEET, with "
            "the shoes/feet clearly visible resting at the bottom of the frame and "
            "the whole body and complete garment inside the frame. This is a "
            "complete head-to-toe photograph — do NOT crop out the head or the feet."
        )
        # The full-body view stays full-body for footwear and accessories, so the
        # gallery's first two images look like every other product's. What
        # changes is that the product must not be lost in it.
        if is_footwear:
            prompt += (
                " BOTH SHOES MUST BE FULLY VISIBLE AND UNOBSTRUCTED at the bottom "
                "of the frame — they are the product. Nothing may cover or break "
                "over them, and the model stands so that both are seen clearly."
            )
        elif is_accessory:
            prompt += (
                f" THE ACCESSORY AT THE {region.upper()} MUST BE FULLY VISIBLE AND "
                "UNOBSTRUCTED — it is the product, worn naturally and never hidden "
                "by hair, a sleeve or an arm."
            )
    elif is_three_quarter:
        if is_footwear:
            prompt += (
                " Capture a LOWER-LEG three-quarter shot focused on the FOOTWEAR: "
                "frame from around the KNEE all the way DOWN TO THE FLOOR, so both "
                "shoes fill most of the frame and are the clear subject. The camera "
                "moves IN CLOSER than the full-body shot and the torso, head and "
                "upper legs are OUT of frame. This must look clearly different from "
                "the full-body shot — a tight, floor-level framing centred on the "
                "shoes. IMPORTANT: the front reference image is provided ONLY for "
                "the model's identity and appearance — do NOT copy its full-length "
                "framing; recompose this shot tighter on the feet."
            )
        elif is_accessory:
            prompt += (
                f" Capture a three-quarter shot cropped to the {region}, focused on "
                "the ACCESSORY: the camera moves IN CLOSER than the full-body shot "
                "so the product fills most of the frame and is unmistakably the "
                "subject, while still reading as worn on a person. This must look "
                "clearly different from the full-body shot. IMPORTANT: the front "
                "reference image is provided ONLY for the model's identity and "
                "appearance — do NOT copy its full-length framing; recompose this "
                "shot tighter on the product."
            )
        elif is_bottom:
            prompt += (
                " Capture a LOWER-BODY three-quarter shot focused on the bottoms "
                "(trousers/skirt/shorts): frame from around the WAIST (the top of "
                "the bottoms) all the way DOWN TO THE FEET, so the bottoms garment "
                "and the legs fill most of the frame, with the shoes/feet visible at "
                "the bottom edge. The camera moves IN CLOSER than the full-body shot "
                "and the head and upper chest are mostly OUT of frame. This must "
                "look clearly different from the full-body shot — a tighter, "
                "lower-body framing centred on the bottoms. IMPORTANT: the front "
                "reference image is provided ONLY for the model's identity and "
                "appearance — do NOT copy its full-length framing; recompose this "
                "shot tighter on the lower body."
            )
        else:
            prompt += (
                " Capture a THREE-QUARTER-LENGTH (knee-up) shot that is distinctly "
                "TIGHTER and more zoomed-in than a full-body photo. The camera moves "
                "IN CLOSER so the model is noticeably LARGER in the frame and the "
                "upper body and garment fill most of the image. The bottom edge of "
                "the frame CUTS ACROSS THE LEGS just below the knees: the lower "
                "legs, ankles, shoes and FEET are deliberately CROPPED OUT and MUST "
                "NOT be visible. Keep the head fully in frame. This is explicitly "
                "NOT a full-length head-to-toe shot — the feet are cut off by the "
                "bottom of the frame. IMPORTANT: the front reference image is "
                "provided ONLY for the model's identity and appearance — do NOT copy "
                "its full-length framing; recompose this shot tighter (knee-up)."
            )

    prompt += (
        f" {view_description}. High quality, realistic lighting, high resolution. "
        f"Use all provided images as reference for accurate details, colors, "
        f"textures, and design elements. Return ONLY the generated image."
    )

    # Free-text add-ons the structured builder has no slot for. The regenerate
    # modal appends these rather than routing them through the description, and
    # they are appended in the same order here.
    lighting = _trait(s.lighting_texture)
    if lighting and lighting.lower() != "none":
        prompt += f" Lighting style: {lighting}."
    if s.realistic_skin_details:
        prompt += (
            " Include realistic skin details like freckles, pores, and fine lines "
            "for authenticity."
        )

    # The tenant's own prompt goes FIRST, exactly as banana-nano.ts places it.
    # A tenant that has written a full specification — BOAS's is 2,825 characters
    # covering garment fidelity, background, exposure and styling — expects it to
    # lead, and the analyze worker composes it the same way. Putting it last, or
    # letting it replace the structured text, would make renders from this path
    # differ from the ones already in the gallery.
    effective_custom = ctx.custom_prompt or s.custom_prompt
    return f"{effective_custom} {prompt}" if effective_custom else prompt


# --------------------------------------------------------------------------- #
# Calling the model
# --------------------------------------------------------------------------- #

class NanoBanana:
    """One generation session for one product."""

    def __init__(self, api_keys: str | list[str], pol: dict[str, Any]) -> None:
        from google import genai  # imported lazily so the service boots without it
        from google.genai import types

        self.genai = genai
        # A list, always. Accepting a bare string too keeps the constructor
        # usable from a test or a one-off script without ceremony.
        self.api_keys = [api_keys] if isinstance(api_keys, str) else list(api_keys)
        self._key_index = 0
        self._key_lock = threading.Lock()
        self.cfg = (pol.get("imagery") or {}).get("generation") or {}
        self.model = self.cfg.get("model") or "gemini-3-pro-image-preview"
        self.calls = 0
        self.errors: list[str] = []

        # A render takes minutes, so the SDK's default read timeout is far too
        # short — and on a host that stalls on IPv6, `client_args` is the only way
        # in: the SDK builds its own httpx client, so the transport has to be
        # handed to it rather than configured around it.
        self._timeout_ms = int(float(self.cfg.get("timeout_s") or 300) * 1000)

    def _http_options(self):
        """FRESH HttpOptions — and a fresh transport — for every call.

        Built per call, not once in __init__, and that is the whole point.
        `genai_client_args()` returns an `httpx.HTTPTransport`, which owns a
        connection pool. Cached on the instance, every per-thread `genai.Client`
        got the SAME transport: the four views that run concurrently shared one
        pool, and the moment the first client finished and closed it, the others
        lost their sockets mid-read.

        The symptom was three simultaneous
        `ReadError: [WinError 10038] An operation was attempted on something
        that is not a socket` in the same second one view succeeded — reported
        as three failed views, and indistinguishable in the logs from a model
        refusing the garment.
        """
        from google.genai import types

        return types.HttpOptions(
            timeout=self._timeout_ms,
            client_args=genai_client_args() or None,
        )

    def _next_key(self) -> str:
        """The next generation key, round-robin.

        Locked because views generate on a thread pool: an unguarded
        read-modify-write would hand the same key to two concurrent calls and
        skip another, which is exactly the per-key rate-limit pressure the
        rotation exists to spread.
        """
        with self._key_lock:
            key = self.api_keys[self._key_index % len(self.api_keys)]
            self._key_index += 1
        return key

    # ------------------------------------------------------------------ inputs
    def fetch(self, urls: list[str], timeout: float = 30.0) -> dict[str, bytes]:
        """Download source photographs, concurrently and under a deadline.

        Keyed BY URL, never a positional list. An earlier version returned a list
        with the failures dropped, which quietly renumbered everything after
        them: when a 6 MB front photo truncated mid-download, the caller's
        `buffers[0]` became the BACK photograph and the model was asked to render
        a front view from it. Nothing errored and the output looked plausible.

        Missing keys are the caller's signal that a specific photograph is
        unavailable, which is a decision only it can make — a missing back is
        recoverable, a missing front is not.
        """
        got = fetch_all(urls, timeout_s=timeout, deadline_s=timeout * 2)
        out: dict[str, bytes] = {}
        for url in urls:
            data = got.get(url)
            if data is None:
                msg = f"source fetch failed: {url[:70]}"
                log.warning(msg)
                self.errors.append(msg)
                continue
            out[url] = compress_source(data)
        return out

    # ------------------------------------------------------------------- calls
    def _one(
        self,
        view: str,
        front: bytes,
        back: bytes | None,
        ctx: PromptContext,
        additional: list[bytes],
        front_reference: bytes | None,
        model: str | None = None,
    ) -> tuple[bytes | None, str | None]:
        """One view on one model. Returns (bytes, error) — exactly one is set."""
        from google.genai import types

        model = model or self.model

        prompt = build_prompt(view, ctx, has_front_reference=front_reference is not None)

        parts: list[Any] = [
            types.Part.from_text(text=prompt),
            types.Part.from_bytes(data=front, mime_type="image/jpeg"),
        ]
        if back is not None:
            parts.append(types.Part.from_bytes(data=back, mime_type="image/jpeg"))
        # The reference rides along for every view but the front — which, in a
        # set, IS the reference — unless the identity is being copied from a
        # render the product already has, in which case the front needs it too.
        if front_reference is not None and (view != "front" or ctx.identity_from_reference):
            parts.append(types.Part.from_text(
                text="This is the front view reference - use the EXACT SAME model "
                     "with identical characteristics."
            ))
            parts.append(types.Part.from_bytes(
                data=front_reference, mime_type="image/jpeg"
            ))
        for extra in additional:
            parts.append(types.Part.from_bytes(data=extra, mime_type="image/jpeg"))

        image_config: dict[str, Any] = {
            "image_size": resolve_image_size(
                ctx.settings.resolution, self.cfg.get("default_resolution") or "2K"
            )
        }
        ratio = resolve_aspect_ratio(
            ctx.settings.aspect_ratio, self.cfg.get("supported_aspect_ratios") or []
        )
        if ratio:
            image_config["aspect_ratio"] = ratio

        # A fresh client per call, on the NEXT key, so parallel views spread
        # across the configured keys rather than hammering one — the same
        # `makeClient()`-per-view rotation banana-nano.ts does.
        client = self.genai.Client(
            api_key=self._next_key(),
            http_options=self._http_options(),
        )
        # EXPLICIT SAFETY THRESHOLDS.
        #
        # Left unset, the developer API applies BLOCK_MEDIUM_AND_ABOVE — stricter
        # than Google's own consumer surface, which renders a player-name jersey
        # on a model (back view included) while the identical garment through
        # this API returns IMAGE_OTHER. These are a documented request parameter
        # for exactly this: tuning the threshold to the domain. Second-hand
        # clothing shot for resale is a benign one.
        #
        # A threshold move, not a way around a decision — and it may not help at
        # all, because an image refusal can originate in an output-side filter
        # these do not reach. `safety_relaxed: false` restores the defaults.
        safety = None
        if self.cfg.get("safety_relaxed"):
            try:
                low = types.HarmBlockThreshold.BLOCK_ONLY_HIGH
                safety = [
                    types.SafetySetting(category=c, threshold=low)
                    for c in (
                        types.HarmCategory.HARM_CATEGORY_HARASSMENT,
                        types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                        types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                        types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                    )
                ]
            except AttributeError as exc:
                # An SDK that names these differently must not take generation
                # down with it — fall back to the API defaults.
                log.warning("safety settings unavailable in this SDK: %s", exc)

        config = types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(**image_config),
            **({"safety_settings": safety} if safety else {}),
        )
        contents = [types.Content(role="user", parts=parts)]

        # Transient server errors are retried HERE rather than by the caller,
        # for the same reason the TypeScript retries a 429 inside the view rather
        # than in the worker: the worker would re-run the whole job, redoing the
        # views that already succeeded. Observed in practice — a 504
        # DEADLINE_EXCEEDED four seconds into a request that normally takes
        # twenty-five, on a product whose other view was fine.
        #
        # A REFUSAL is never retried here. It is a decision, not a fault, and
        # repeating the identical request gets the identical answer while
        # doubling the latency the operator waits through.
        attempts = int(self.cfg.get("max_retries") or 2) + 1
        backoff = float(self.cfg.get("retry_backoff_s") or 3)
        last = ""
        for attempt in range(attempts):
            self.calls += 1
            try:
                resp = client.models.generate_content(
                    model=model, contents=contents, config=config
                )
                break
            except Exception as exc:  # noqa: BLE001 — one view failing is survivable
                last = f"{type(exc).__name__}: {exc}"
                if attempt + 1 >= attempts or not _is_transient(last):
                    log.warning("nano banana call failed (%s on %s: %s)", view, model, last)
                    return None, last
                log.info("%s failed (%s); retry %d/%d",
                         view, last, attempt + 1, attempts - 1)
                time.sleep(backoff * (attempt + 1))
        else:  # pragma: no cover — the loop always breaks or returns
            return None, last

        for candidate in resp.candidates or []:
            for part in (candidate.content.parts if candidate.content else []) or []:
                inline = getattr(part, "inline_data", None)
                if inline and inline.data:
                    return inline.data, None

        # No image AND no exception — almost always a content decision rather
        # than a fault. Reporting a bare "no image returned" here sent a real
        # investigation down the wrong path for an hour, chasing prompt length
        # and quota when the model was in fact declining a Raptors jersey with a
        # player's name on the back.
        #
        # THREE places carry the reason, and only checking the first left an
        # Aaron Rodgers jersey reported as "no reason given":
        #   * candidate.finish_reason — the usual IMAGE_OTHER / IMAGE_SAFETY
        #   * prompt_feedback.block_reason — set when the REQUEST is blocked
        #     outright, in which case `candidates` is empty and the first check
        #     finds nothing
        #   * a text part — the model sometimes answers in words instead
        parts_of_reason: list[str] = []

        block = getattr(getattr(resp, "prompt_feedback", None), "block_reason", None)
        if block:
            parts_of_reason.append(f"prompt blocked: {block}")

        for candidate in resp.candidates or []:
            finish = getattr(candidate, "finish_reason", None)
            if finish:
                parts_of_reason.append(str(finish))
            for part in (candidate.content.parts if candidate.content else []) or []:
                said = (getattr(part, "text", "") or "").strip()
                if said:
                    parts_of_reason.append(f'model replied: "{said[:160]}"')
            break

        reason = " — ".join(parts_of_reason) or "no image and no reason given"
        log.warning("nano banana produced no image for %s on %s (%s)",
                    view, model, reason)
        return None, reason

    # ----------------------------------------------------------------- the run
    def generate(
        self,
        views: list[str],
        front: bytes,
        back: bytes | None,
        ctx: PromptContext,
        additional: list[bytes] | None = None,
        front_reference: bytes | None = None,
        preferred_model: str | None = None,
    ) -> list[GeneratedView]:
        """Render `views` (VNYX view names) with ONE model, and hand back the bytes.

        ONE MODEL FOR THE WHOLE SET. This used to escalate per view, so a garment
        the primary would render from the front but not from the back came out as
        a Gemini front beside a gpt-image back — two different people in one
        product gallery, which is worse than a missing image because it ships
        looking deliberate.

        The escalation is therefore over the SET: every requested view is tried
        on one model, and only if that model cannot do all of them does the next
        one get a turn. The common case costs exactly what it did before, one
        call per view on the primary; only a product that needs a fallback pays
        for the retries, and it gets a consistent set in exchange.

        `preferred_model` goes to the front of the chain. The caller passes
        whatever produced the renders already on the product, so a gap-fill keeps
        the model that is already in the gallery instead of introducing a second.

        `front_reference` is what keeps one model IDENTITY across a set. When the
        caller supplies one — an AI_FRONT the product already has — every view is
        generated against it. When it does not, the front is generated FIRST and
        becomes the reference for the rest, which is the TypeScript's sequencing
        and the reason the front cannot simply join the parallel batch.
        """
        started = time.perf_counter()
        wanted = [MEDIA_TO_VIEW[v] for v in views if v in MEDIA_TO_VIEW]
        wanted.sort(key=lambda v: VIEW_ORDER.index(v))
        if not wanted:
            return []

        # No back photograph: the front stands in for it, and the prompt says so.
        back_bytes = back if back is not None else front
        extras = (additional or [])[: int(self.cfg.get("max_context_images") or 1)]

        # Every view any model managed, keyed by view. The FIRST model to produce
        # one wins, so a view the primary rendered is never replaced by a later,
        # weaker model's version of it.
        salvage: dict[str, GeneratedView] = {}
        last: list[GeneratedView] = []
        self._attempts: list[list[GeneratedView]] = []

        for model in self._model_chain(preferred_model):
            attempt = self._render_set(
                wanted, front, back_bytes, ctx, extras, front_reference, model
            )
            last = attempt
            self._attempts.append(attempt)
            produced = sum(1 for v in attempt if v.ok)

            if produced == len(wanted):
                if model != self.model:
                    self.errors.append(
                        f"{self.model} could not render every view; the whole set "
                        f"was produced with {model} instead, so they match"
                    )
                self._log_done(attempt, started)
                return attempt

            for view in attempt:
                if view.ok and view.view not in salvage:
                    salvage[view.view] = view
            if produced:
                log.info(
                    "%s rendered %d/%d views; trying the next model for a "
                    "complete set", model, produced, len(wanted),
                )

        # NO single model could do the whole set. Consistency is now unreachable,
        # so the choice is between a complete set from several models and an
        # incomplete one from a single model.
        #
        # Completeness wins, LOUDLY. Discarding a view another model already
        # rendered — which is what keeping one partial did — hands back "could
        # not generate the front" while a perfectly good front sits in memory.
        # A mixed set with a warning is something an operator can look at and
        # judge; a missing image is not.
        if not self.cfg.get("allow_mixed_models", True):
            # Consistency chosen over completeness: hand back the single model's
            # most complete attempt and report the rest as missing.
            best = max(
                self._attempts, key=lambda a: sum(1 for v in a if v.ok), default=[]
            )
            self._log_done(best, started)
            return best

        merged = [salvage[v.view] for v in last if v.view in salvage]
        for view in last:
            if view.view not in salvage:
                merged.append(view)          # keep the failure and its reason
        merged.sort(key=lambda v: VIEW_ORDER.index(MEDIA_TO_VIEW[v.view]))

        models = {v.model for v in merged if v.ok and v.model}
        if len(models) > 1:
            self.errors.append(
                "MIXED MODELS: no single model would render every view, so these "
                f"came from {', '.join(sorted(models))}. They will not look like "
                "the same person — regenerate the set if that matters more than "
                "having the images."
            )

        self._log_done(merged, started)
        return merged

    def _log_done(self, views: list[GeneratedView], started: float) -> None:
        log.info(
            "generated %d/%d views in %.1fs",
            sum(1 for v in views if v.ok), len(views),
            time.perf_counter() - started,
        )

    def _model_chain(self, preferred: str | None) -> list[str]:
        """Every model to try, in order, deduplicated.

        The OpenAI entry is last and only present when it is configured and
        switched on: a different vendor, reached once no Gemini model will take
        the garment.
        """
        chain = [self.model, *(self.cfg.get("fallback_models") or [])]
        if self.cfg.get("openai_fallback") and openai_image.available():
            chain.append(os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1"))
        if preferred:
            chain.insert(0, preferred)

        seen: set[str] = set()
        return [m for m in chain if m and not (m in seen or seen.add(m))]

    def _render_set(
        self,
        wanted: list[str],
        front: bytes,
        back: bytes,
        ctx: PromptContext,
        extras: list[bytes],
        front_reference: bytes | None,
        model: str,
    ) -> list[GeneratedView]:
        """Every requested view, on ONE model."""
        results: dict[str, tuple[bytes | None, str | None]] = {}
        reference = front_reference
        remaining = list(wanted)

        # The front leads when nothing else establishes the identity, because
        # every other view is generated against it.
        if "front" in remaining and reference is None:
            results["front"] = self._render(
                "front", front, back, ctx, extras, None, model
            )
            reference = results["front"][0]
            remaining.remove("front")

        # The rest depend only on the reference, so they run concurrently — the
        # difference between ~front + 1 view and five in series, which for a
        # button on a product page is minutes.
        if remaining:
            with concurrent.futures.ThreadPoolExecutor(
                max_workers=len(remaining)
            ) as pool:
                futures = {
                    pool.submit(
                        self._render, v, front, back, ctx, [], reference, model
                    ): v
                    for v in remaining
                }
                for future in concurrent.futures.as_completed(futures):
                    results[futures[future]] = future.result()

        # SECOND PASS, same model: a front-facing view that failed may have been
        # blocked by the BACK photograph, which it never needed. Proven on a
        # Raptors jersey whose front reads "TORONTO 10" and whose back reads
        # "DEROZAN 10" — the front renders once the back is out of the request.
        #
        # Retried on the SAME model rather than by escalating, so recovering the
        # view cannot introduce a second model into the set. Never attempted for
        # back views: dropping the back photo there does not route around the
        # refusal, it invents the reverse of a licensed garment.
        retryable = [
            v for v in wanted
            if v not in ("back", "back34")
            and results.get(v, (None, None))[0] is None
            and not _is_transient(results.get(v, (None, None))[1])
        ]
        for view in retryable:
            log.info("%s empty on %s; retrying without the back reference",
                     view, model)
            data, error = self._render(
                view, front, None, ctx, extras if view == "front" else [],
                reference, model,
            )
            if data is not None:
                self.errors.append(
                    f"{VIEW_TO_MEDIA[view]}: {model} produced nothing with both "
                    f"photographs attached; generated from the front alone"
                )
                results[view] = (data, None)
                if view == "front" and reference is None:
                    reference = data

        out: list[GeneratedView] = []
        for view in VIEW_ORDER:
            if view not in results:
                continue
            data, error = results[view]
            if error:
                self.errors.append(f"{VIEW_TO_MEDIA[view]} on {model}: {error}")
            out.append(GeneratedView(
                view=VIEW_TO_MEDIA[view],
                image_base64=base64.b64encode(data).decode() if data else None,
                mime_type="image/jpeg",
                bytes=len(data) if data else 0,
                ok=data is not None,
                error=error,
                model=model if data else None,
            ))
        return out

    def _render(
        self,
        view: str,
        front: bytes,
        back: bytes | None,
        ctx: PromptContext,
        additional: list[bytes],
        front_reference: bytes | None,
        model: str,
    ) -> tuple[bytes | None, str | None]:
        """One view on one model, whichever vendor that model belongs to."""
        if _is_openai_model(model):
            # The front reference is passed HERE too. Omitting it is what let a
            # gpt-image back view invent a different person from the Gemini front
            # standing beside it in the gallery.
            images = [front]
            if back is not None and back is not front:
                images.append(back)
            if front_reference is not None and view != "front":
                images.append(front_reference)
            self.calls += 1
            # THE SHAPE THE PRIMARY WOULD HAVE PRODUCED — which is what this
            # render has to match, since the two sit side by side in one gallery
            # and the product page crops whatever does not fit.
            #
            # Not the tenant's raw setting: Gemini is given
            # `resolve_aspect_ratio(...)`, and a 5:7 tenant has no native Gemini
            # equivalent so it becomes 3:4. Conforming to 5:7 would leave the two
            # vendors a different shape from each other.
            #
            # And not nothing when the tenant says "auto": that is the common
            # case here, and it means Gemini renders unconstrained at its own
            # 27:38 while gpt-image lands on 2:3. `auto_portrait_ratio` is that
            # measured Gemini default.
            resolved_ratio = resolve_aspect_ratio(
                ctx.settings.aspect_ratio,
                self.cfg.get("supported_aspect_ratios") or [],
            ) or self.cfg.get("auto_portrait_ratio")
            return openai_image.generate(
                build_prompt(
                    view, ctx, has_front_reference=front_reference is not None
                ),
                images,
                aspect_ratio=resolved_ratio,
                timeout_s=float(self.cfg.get("timeout_s") or 300),
                quality=self.cfg.get("openai_quality"),
            )

        return self._one(
            view, front, back, ctx, additional, front_reference, model=model
        )


def _is_openai_model(model: str) -> bool:
    return model.lower().startswith(("gpt-image", "dall-e"))


# Finish reasons that mean "the model chose not to", as opposed to a fault.
# Retrying the same request unchanged will not help; the caller needs to know
# the difference so it does not present a policy refusal as a transient error.
_REFUSAL_REASONS = (
    "IMAGE_OTHER", "IMAGE_SAFETY", "IMAGE_PROHIBITED_CONTENT",
    "PROHIBITED_CONTENT", "SAFETY", "RECITATION", "BLOCKLIST",
)


def _is_refusal(error: str | None) -> bool:
    return bool(error) and any(r in error.upper() for r in _REFUSAL_REASONS)


# Faults worth trying again: the provider being briefly unable, not unwilling.
# 504 DEADLINE_EXCEEDED is the one seen most on this model, and it arrives in
# seconds rather than at the end of a long generation.
_TRANSIENT_MARKERS = (
    "429", "500", "502", "503", "504",
    "DEADLINE_EXCEEDED", "UNAVAILABLE", "INTERNAL", "RESOURCE_EXHAUSTED",
    "CONNECTERROR", "READTIMEOUT", "REMOTEPROTOCOLERROR", "TIMEOUT",
    # The httpx transport family. `READTIMEOUT` was here but `READERROR` was
    # not, and they are different exceptions: a socket that DIES mid-read raises
    # ReadError, which matched nothing and was therefore classified as a
    # REFUSAL — so a broken connection was reported as "the model declined this
    # garment", and the caller stopped instead of retrying.
    #
    # Seen as `ReadError: [WinError 10038] An operation was attempted on
    # something that is not a socket`, three views at once.
    "READERROR", "WRITEERROR", "POOLTIMEOUT", "PROXYERROR",
    "LOCALPROTOCOLERROR", "SSLERROR", "CLOSEDRESOURCEERROR",
    # Windows socket errnos, which arrive wrapped rather than named.
    "WINERROR",
)


def _is_transient(error: str | None) -> bool:
    if not error:
        return False
    upper = error.upper()
    # A refusal can carry a 400-ish shape; never let it look retryable.
    if any(r in upper for r in _REFUSAL_REASONS):
        return False
    return any(m in upper for m in _TRANSIENT_MARKERS)
